package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/sileod/portal/internal/auth"
)

const hubPort = 8080

func expose(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: portal expose tailscale|cloudflare [options]")
	}
	switch args[0] {
	case "tailscale":
		return exposeTailscale(args[1:])
	case "cloudflare":
		return exposeCloudflare(args[1:])
	default:
		return fmt.Errorf("unknown exposure provider %q", args[0])
	}
}

func exposeTailscale(args []string) error {
	key := firstNonEmpty(os.Getenv("TAILSCALE_AUTHKEY"), os.Getenv("TS_AUTHKEY"))
	password := firstNonEmpty(os.Getenv("PORTAL_PASSWORD"), os.Getenv("PORTAL_TOKEN"))
	funnelHost := firstNonEmpty(os.Getenv("PORTAL_FUNNEL_HOST"), "portal")
	portalHost := os.Getenv("PORTAL_HOST")
	if portalHost == "" {
		portalHost, _ = os.Hostname()
	}
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--key":
			i++
			if i >= len(args) {
				return errors.New("--key requires a value")
			}
			key = args[i]
		case "--hostname":
			i++
			if i >= len(args) {
				return errors.New("--hostname requires a value")
			}
			funnelHost = args[i]
		case "--host":
			i++
			if i >= len(args) {
				return errors.New("--host requires a value")
			}
			portalHost = args[i]
		default:
			return fmt.Errorf("unknown option %s", args[i])
		}
	}
	if password == "" {
		return errors.New("PORTAL_PASSWORD is required")
	}
	if !validTailscaleHostname(funnelHost) {
		return errors.New("Tailscale host names must be 1-63 letters, digits, or hyphens and cannot start or end with a hyphen")
	}
	if !validHostAlias(portalHost) {
		return errors.New("Portal host name may contain only letters, digits, _, and -")
	}
	if _, err := exec.LookPath("tailscale"); err != nil {
		return errors.New("tailscale is required")
	}
	if key != "" {
		if !strings.HasPrefix(key, "tskey-") {
			return errors.New("Tailscale auth keys are generated by Tailscale and start with tskey-")
		}
		if err := tailscaleUpKey(key); err != nil {
			return err
		}
	} else if exec.Command("tailscale", "status").Run() != nil {
		if err := tailscaleUpInteractive(); err != nil {
			return err
		}
	}

	out, err := privilegedCommand("tailscale", "set", "--hostname="+funnelHost).CombinedOutput()
	if err != nil {
		return fmt.Errorf("tailscale set hostname: %s", commandOutput(err, out))
	}
	if err := ensureHub(password); err != nil {
		return err
	}
	out, err = privilegedCommand("tailscale", "funnel", "--bg", "--yes", fmt.Sprintf("http://127.0.0.1:%d", hubPort)).CombinedOutput()
	if err != nil {
		return fmt.Errorf("tailscale funnel: %s", commandOutput(err, out))
	}
	url := firstHTTPS(string(out))
	if url == "" || !strings.HasPrefix(strings.TrimPrefix(url, "https://"), funnelHost+".") {
		status, _ := privilegedCommand("tailscale", "funnel", "status").CombinedOutput()
		url = firstHTTPS(string(status))
	}
	if url == "" || !strings.HasPrefix(strings.TrimPrefix(url, "https://"), funnelHost+".") {
		url, err = waitTailscaleURL(funnelHost)
		if err != nil {
			return err
		}
	}
	return finishExpose(url, password, "Tailscale Funnel", portalHost)
}

func exposeCloudflare(args []string) error {
	key := firstNonEmpty(os.Getenv("TUNNEL_TOKEN"), os.Getenv("CLOUDFLARE_TUNNEL_TOKEN"))
	url := strings.TrimRight(os.Getenv("PORTAL_URL"), "/")
	password := firstNonEmpty(os.Getenv("PORTAL_PASSWORD"), os.Getenv("PORTAL_TOKEN"))
	portalHost := os.Getenv("PORTAL_HOST")
	if portalHost == "" {
		portalHost, _ = os.Hostname()
	}
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--key":
			i++
			if i >= len(args) {
				return errors.New("--key requires a value")
			}
			key = args[i]
		case "--url":
			i++
			if i >= len(args) {
				return errors.New("--url requires a value")
			}
			url = strings.TrimRight(args[i], "/")
		case "--host":
			i++
			if i >= len(args) {
				return errors.New("--host requires a value")
			}
			portalHost = args[i]
		default:
			return fmt.Errorf("unknown option %s", args[i])
		}
	}
	if key == "" || url == "" || password == "" {
		return errors.New("CLOUDFLARE_TUNNEL_TOKEN, PORTAL_PASSWORD, and --url are required")
	}
	if !validHostAlias(portalHost) {
		return errors.New("Portal host name may contain only letters, digits, _, and -")
	}
	if _, err := exec.LookPath("cloudflared"); err != nil {
		return errors.New("cloudflared is required")
	}
	if err := ensureHub(password); err != nil {
		return err
	}
	if err := ensureCloudflared(key); err != nil {
		return err
	}
	return finishExpose(url, password, "Cloudflare Tunnel", portalHost)
}

func tailscaleUpInteractive() error {
	cmd := privilegedCommand("tailscale", "up")
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("tailscale sign-in: %w", err)
	}
	return nil
}

func tailscaleUpKey(key string) error {
	keyFile, err := os.CreateTemp("", "portal-tailscale-key-*")
	if err != nil {
		return err
	}
	path := keyFile.Name()
	defer os.Remove(path)
	if err := keyFile.Chmod(0600); err != nil {
		keyFile.Close()
		return err
	}
	if _, err := keyFile.WriteString(key + "\n"); err != nil {
		keyFile.Close()
		return err
	}
	if err := keyFile.Close(); err != nil {
		return err
	}

	cmd := privilegedCommand("tailscale", "up", "--auth-key=file:"+path)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("tailscale up: %w", err)
	}
	return nil
}

func privilegedCommand(name string, args ...string) *exec.Cmd {
	if os.Geteuid() != 0 {
		if _, err := exec.LookPath("sudo"); err == nil {
			return exec.Command("sudo", append([]string{name}, args...)...)
		}
	}
	return exec.Command(name, args...)
}

func tailscaleURL() (string, error) {
	out, err := exec.Command("tailscale", "status", "--json").Output()
	if err != nil {
		return "", errors.New("could not determine Tailscale Funnel URL")
	}
	var status struct {
		Self struct {
			DNSName string `json:"DNSName"`
		} `json:"Self"`
	}
	if json.Unmarshal(out, &status) != nil || status.Self.DNSName == "" {
		return "", errors.New("could not determine Tailscale Funnel URL")
	}
	return "https://" + strings.TrimSuffix(status.Self.DNSName, "."), nil
}

func waitTailscaleURL(hostname string) (string, error) {
	for range 40 {
		url, err := tailscaleURL()
		if err == nil && strings.HasPrefix(strings.TrimPrefix(url, "https://"), hostname+".") {
			return url, nil
		}
		time.Sleep(250 * time.Millisecond)
	}
	return "", errors.New("Tailscale hostname changed, but the new Funnel URL was not visible yet; rerun `portal` in a moment")
}

func ensureHub(password string) error {
	if processRunning(hubPIDPath()) {
		return nil
	}
	if err := os.MkdirAll(configDir(), 0700); err != nil {
		return err
	}
	logFile, err := os.OpenFile(hubLogPath(), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0600)
	if err != nil {
		return err
	}
	cmd := exec.Command(os.Args[0], "hub")
	cmd.Env = append(os.Environ(), "PORTAL_PASSWORD="+password, fmt.Sprintf("PORTAL_ADDR=127.0.0.1:%d", hubPort))
	cmd.Stdin = nil
	cmd.Stdout, cmd.Stderr = logFile, logFile
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		logFile.Close()
		return err
	}
	logFile.Close()
	if err := os.WriteFile(hubPIDPath(), []byte(strconv.Itoa(cmd.Process.Pid)+"\n"), 0600); err != nil {
		return err
	}
	for range 20 {
		if processRunning(hubPIDPath()) {
			return nil
		}
		time.Sleep(25 * time.Millisecond)
	}
	return errors.New("hub did not start; see " + hubLogPath())
}

func ensureCloudflared(key string) error {
	if processRunning(cloudflarePIDPath()) {
		return nil
	}
	logFile, err := os.OpenFile(cloudflareLogPath(), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0600)
	if err != nil {
		return err
	}
	cmd := exec.Command("cloudflared", "tunnel", "run")
	cmd.Env = append(os.Environ(), "TUNNEL_TOKEN="+key)
	cmd.Stdin = nil
	cmd.Stdout, cmd.Stderr = logFile, logFile
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		logFile.Close()
		return err
	}
	logFile.Close()
	return os.WriteFile(cloudflarePIDPath(), []byte(strconv.Itoa(cmd.Process.Pid)+"\n"), 0600)
}

func finishExpose(url, password, provider, host string) error {
	cfg := config{URL: strings.TrimRight(url, "/"), Token: auth.AgentToken(password), Host: host}
	if err := saveConfig(cfg); err != nil {
		return err
	}
	if err := restartDaemon(); err != nil {
		return err
	}
	fmt.Printf("✓ %s\nPortal: %s\nHost: %s\nPassword: configured\n", provider, cfg.URL, cfg.Host)
	return nil
}

func processRunning(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	return err == nil && pid > 0 && syscall.Kill(pid, 0) == nil
}

func firstHTTPS(s string) string {
	for _, field := range strings.Fields(s) {
		field = strings.Trim(field, "|()[]{}<>,;\"'")
		if strings.HasPrefix(field, "https://") {
			return strings.TrimRight(field, "/")
		}
	}
	return ""
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}

func commandOutput(err error, out []byte) string {
	if text := strings.TrimSpace(string(out)); text != "" {
		return text
	}
	return err.Error()
}

func hubPIDPath() string        { return configDir() + "/hub.pid" }
func hubLogPath() string        { return configDir() + "/hub.log" }
func cloudflarePIDPath() string { return configDir() + "/cloudflared.pid" }
func cloudflareLogPath() string { return configDir() + "/cloudflared.log" }
